services:

  application:
    build: ../src
    environment:
      - ANSIBLE_RUNNER_API_PREFIX=dev
    ports:
      - 8000:8000

  database:
    build: ../datastorage
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=11111111
    ports:
      - 5432:5432

  cache:
    build: ../cache
    ports:
      - 6379:6379
