services:

  application:
    build: ../src
    ports:
      - "8000:8000"

  database:
    build: ../datastorage
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=11111111
    ports:
      - 5432:5432
